// define all actions
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const INCREASE_CART_ITEM_COUNT = "INCREASE_CART_ITEM_COUNT";
export const DECREASE_CART_ITEM_COUNT = "DECREASE_CART_ITEM_COUNT";
